### ISSUE TITLE
Example Bug

### ISSUE THREAD

**Issue by johnmuth81** [ToriHoush/vision#2]
An issue will come in like this.

To create it:
1) Select 'Issues' tab in Web UI
2) Press "New Issue" button
3) Fill in the fields
4) Press "Submit new issue" button.

**Comment by ToriHoush** [comment]
1. 1. so this is a bug report. 
2. 2. and any attention to the bug itself is recognized by a pull request showing up.
3. 3. and the light editor buttons are cute
4. and this issue is unrelated to #1

**Comment by ToriHoush** [comment]
and eventually when the issue is resolved it is then presented as a pull request perhaps.
